### ISSUE TITLE
Add docs for Datasets

### ISSUE THREAD

**Issue by abhi18av** [seqeralabs/nf-tower-docs#104]

**Comment by pditommaso** [comment]
Should not be submenus on the sidebar for Dataset? 

![Uploading Screenshot 2021-10-04 at 14.37.55.png…]()

**Comment by abhi18av** [comment]
> Should not be submenus on the sidebar for Dataset?

Not really, sub-menus are for bigger topics like `Compute Environments` etc. 

I could add a `Datasets/Overview` if you'd like to see a submenu there, but not sure if it makes sense for one page content to ask user for two-clicks.

**Comment by pditommaso** [comment]
Ok, no pb
