### ISSUE TITLE
Create a top level menu item for the CLI

### ISSUE THREAD

**Issue by evanfloden** [seqeralabs/nf-tower-docs#116]
Currently, the CLI is under the API menu item.

Moving it to the top level would give more visibility. The content for the page can be similar to the README and referencing GH for all the important info.

# Nextflow Tower CLI

`tw` is [Tower](https://landing.tower.nf/) on the command line. It brings Tower concepts including Pipelines, Actions and Compute Environments to the terminal.

Tower is a full-stack application for the management of data pipelines and compute resources. It enables collaborative data analysis at scale, on-premises or in any cloud.

The Tower CLI interacts with Tower, providing an interface to launch pipelines, manage cloud resources and administer your analysis.

![tw](assets/img/tw-screenshot.png)

The key features are:

- **A Nextflow-like experience**: Tower CLI provides a developer-friendly environment. Pipelines can be launched with the CLI similar to Nextflow but with the benefits of Tower such as monitoring, logging, resource provisioning, dataset management, and collaborative sharing.

- **Infrastructure as Code**: All Tower resources including Pipelines and Compute Environments can be described in a declarative manner. This allows a complete definition of an analysis environment that can be versioned and treated as code. It greatly simplifies sharing and re-use of configuration as well as routine administration.

- **Built on OpenAPI**: Tower CLI interacts with Tower via the [Tower API](https://tower.nf/openapi/index.html) which is created using the latest OpenAPI 3.0 specification. Tower CLI provides full control of the Tower application allowing users to get maximum insights into their pipeline submissions and execution environments.

For more information on Tower, see the [user documentation](https://help.tower.nf) on the Tower Cloud website.

## Availability

Tower CLI can be installed on macOS, Windows, and Linux.

Visit the [Tower CLI](https://github.com/seqeralabs/tower-cli/) page on GitHub for installation and configuration details.

**Comment by abhi18av** [comment]
@evanfloden , I've updated the docs for the CLI and this is deployed here https://nf-tower-docs-master-html.netlify.app/21.10/cli/ - in addition to the fonts.

Let me if that's looking okay. 

From my side, the help docs are good to be deployed to prod.

**Comment by abhi18av** [comment]
Closing this issue as the CLI page is on prod already.
https://help.tower.nf/21.12/cli/#availability
