### ISSUE TITLE
Create Documentation section about secrets (user and pipeline)

### ISSUE THREAD

**Issue by swampie** [seqeralabs/nf-tower-docs#124]
Create documentation about the secret functionality by
- [x] Adding the relevant description inside the Core Concepts section
- [x] Describe the flow of the secrets and how it maps in various environment (AWS and SLURM/HPC)
- [x] Describe the difference about user secrets and pipeline secrets 
- [x] Screenshots

**Comment by abhi18av** [comment]
Marking this as done since it was merged and released already - Thanks Matteo!
