### ISSUE TITLE
Add docs on stting up dockerhub credentials

### ISSUE THREAD

**Issue by achristofferson-bbi** [seqeralabs/nf-tower-docs#163]
I am trying to run a workflow that uses tower, google, and private dockerhub repos and cannot get the credentials to work. permission denied/does not exist when pulling the private dockerhub image. Is this possible or a limitation of using tower with google life sciences?

**Comment by bentsherman** [comment]
As far as I can remember, the only way we support private docker repos at the moment is through Kubernetes. See https://github.com/nextflow-io/nextflow/issues/2827 for details. It is handled through Nextflow and your K8s cluster, so Tower isn't involved. We may add more comprehensive support through Tower in the future, but I don't know what the expected timeframe is.

**Comment by abhi18av** [comment]
Hi @achristofferson-bbi ,

Building upon what Ben mentioned, it is possible to add docker registry credentials (with limited support, see below)

I'd just like to add that this functionality is only available for Azure Batch at the moment, and we are working hard on making this generally available to all platforms.


![image](https://user-images.githubusercontent.com/12799326/173352683-dd96311e-f6db-4725-b2db-50e786cbb938.png)

**Comment by llewellyn-sl** [comment]
Hi @achristofferson-bbi. Circling back on this issue from last year to let you know that as of version 22.4, Tower supports private registry authentication via the [Wave containers](https://help.tower.nf/23.1/enterprise/configuration/wave/) service. Tower supports  support [Docker Hub](https://help.tower.nf/23.1/credentials/docker_hub_registry_credentials/),
[AWS Elastic Container Registry], (https://help.tower.nf/23.1/credentials/aws_registry_credentials/),
[Azure Container Registry](https://help.tower.nf/23.1/credentials/azure_registry_credentials/),
[Google Cloud](https://help.tower.nf/23.1/credentials/google_registry_credentials/), and 
[Quay](https://help.tower.nf/23.1/credentials/quay_registry_credentials/) registries. 

See also info on Wave containers in [Tower](https://help.tower.nf/23.1/enterprise/configuration/wave/) and [Nextflow](https://www.nextflow.io/docs/latest/wave.html).
