### ISSUE TITLE
Add markdownlint

### ISSUE THREAD

**Issue by drpatelh** [seqeralabs/nf-tower-docs#203]
It would be good to lint the markdown docs in this repo. We can copy across the Action from the Tower CLI [here](https://github.com/seqeralabs/tower-cli/blob/master/.github/workflows/lint-markdown.yml)

**Comment by drpatelh** [comment]
You should be able to with an exceptions file with rules that you want to ignore:
https://github.com/nf-core/rnaseq/blob/3.6/.markdownlint.yml

I pasted [this](https://raw.githubusercontent.com/seqeralabs/nf-tower-docs/master/docs/reports/overview.md) existing markdown for Reports into the online tester [here](https://dlaa.me/markdownlint/) and it identified some issues that need to be fixed but was happy with the `!!! tip`.

**Comment by justinegeffen** [comment]
Thanks for opening this! We've just moved our docs to a new service (Docusaurus) and implementing linters is on our Q1 roadmap. I'm going to close this issue as it is being addressed. :)

**Comment by abhi18av** [comment]
Thanks @justinegeffen  - Docusaurus sounds great! 

If it is of any guidance, please feel free to play around the previous attempt mentioned here https://github.com/seqeralabs/nf-tower-docs/issues/52 - looking forward to the new website :)
