### ISSUE TITLE
Anchors are not working with indirect links 

### ISSUE THREAD

**Issue by abhi18av** [seqeralabs/nf-tower-docs#245]
Short description:

🟢 Works => https://help.tower.nf/22.2/compute-envs/aws-batch/#iam-user

🔴 Does not work => https://help.tower.nf/compute-envs/aws-batch/#iam-user

🔴 Does not work => https://help.tower.nf/latest/compute-envs/aws-batch/#iam-user

**Comment by llewellyn-sl** [comment]
Can't remember what previous work fixed this, but works now.
