### ISSUE TITLE
EFS mount path is not optional

### ISSUE THREAD

**Issue by tomsing1** [seqeralabs/nf-tower-docs#246]
When instantiating a new AWS Batch Compute Environment, the EFS mount points are labelled as `optional`, but the they are actually required (see screenshot below). The [documentation](https://github.com/seqeralabs/nf-tower-docs/blob/027b65402f67d23c977d905c4406d015ab394a82/docs/compute-envs/aws-batch.md?plain=1#L142) does not provide instructions on what the best mount point would be - or what the consequences of this choice are. (The FSx options are documented in more detail.)

<img width="665" alt="Screen Shot 2022-09-12 at 2 15 14 PM" src="https://user-images.githubusercontent.com/10490984/189760277-b2d72396-55cc-41f5-96fd-e5a0f64ab30f.png">

**Comment by abhi18av** [comment]
Hi @tomsing1 ,

Thanks for reporting this discrepancy - we're tracking this now on our backlog and will update the UI/docs accordingly.

**Comment by tomsing1** [comment]
@llewellyn-sl Thank you for picking up this issue. Can you perhaps share how the mount path should be specified? E.g. should it be `/efs/work` (similar to `/fsx/work`)? That would be really helpful to know, even before you had time to update the official documentation.

**Comment by llewellyn-sl** [comment]
> @llewellyn-sl Thank you for picking up this issue. Can you perhaps share how the mount path should be specified? E.g. should it be `/efs/work` (similar to `/fsx/work`)? That would be really helpful to know, even before you had time to update the official documentation.

@tomsing1 EFS and FSx steps from upcoming documentation will read:

"16. To use EFS, you can either select Use existing EFS file system and specify an existing EFS instance, or select Create new EFS file system to create one. If you intend to use the EFS file system as your work directory, you will need to specify <your_EFS_mount_path>/work in the Pipeline work directory field(step 8 of this guide).

-To use an existing EFS file system, enter the EFS file system id and EFS mount path. This is the path where the EFS volume is accessible to the compute environment. For simplicity, we advise that you use `/mnt/efs` as the EFS mount path.
-To create a new EFS file system, enter the EFS mount path. We advise that you specify `/mnt/efs` as the EFS mount path.

17. To use FSx for Lustre, you can either select Use existing FSx file system and specify an existing FSx instance, or select Create new FSx file system to create one. If you intend to use the FSx file system as your work directory, you will need to specify `<your_FSx_mount_path>/work` in the Pipeline work directory field (step 8 of this guide).

To use an existing FSx file system, enter the FSx DNS name and FSx mount path. The FSx mount path is the path where the FSx volume is accessible to the compute environment. For simplicity, we advise that you use `/mnt/fsx` as the FSx mount path.
To create a new FSx file system, enter the FSx size (in GB) and the FSx mount path. We advise that you specify `/mnt/fsx` as the FSx mount path." 

I hope that helps.

**Comment by tomsing1** [comment]
Super helpful! Thanks a lot @llewellyn-sl!
