### ISSUE TITLE
Improve the documentation for container credentials

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/nf-tower-docs#253]
The Tower docs is omitting the support for Container registry credentials 

https://help.tower.nf/22.2/credentials/overview/

**Comment by abhi18av** [comment]
Paolo, the plan was to add this in the Azure one but not sure if we should first wait for other developments or add this already?

CC @llewellyn-sl

**Comment by llewellyn-sl** [comment]
Abhi, when you say 'the Azure one', do you mean the Azure section in the Tower docs FAQ? https://help.tower.nf/22.2/faqs/#azure 

If so, it may be better suited to the Credentials section as that is more visible on top level nav.

**Comment by abhi18av** [comment]
> If so, it may be better suited to the Credentials section as that is more visible on top level nav.

In general yes, but the current limitation is that it only works with Azure and no other platform. Therefore depending on other efforts, we can update the docs for the longer term solution. What do you think?
