### ISSUE TITLE
Update AWS docs permissions

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/nf-tower-docs#258]
The just releases Resource Labels feature requires the following changes in the AWS IAM policy used by AWS Compute environment. 

https://github.com/seqeralabs/nf-tower-aws/commit/65b4659d93c0639ea95cc96369865b328a17bb15

The documentation should be updated correspondingly.

**Comment by llewellyn-sl** [comment]
Closed as part of 22.4 and 23.1 updates to docs — https://help.tower.nf/23.1/resource-labels/overview/#aws
