### ISSUE TITLE
Subsection headings get overlapped by the header when navigating to anchor

### ISSUE THREAD

**Issue by tcrespog** [seqeralabs/nf-tower-docs#26]
Navigate to a subsection such as "Introduction > What is Nextflow?" (`https://localhost:1313/docs/welcome/introduction/#what-is-nextflow`). The heading gets overlapped by the header:
![anchor2](https://user-images.githubusercontent.com/10177888/99261077-83c73d00-281c-11eb-9df5-77731df68e30.png)

Does not seem to happen always and with all subsections.

**Comment by abhi18av** [comment]
Is this still applicable to the new docs?
