### ISSUE TITLE
Add Enable Fusion mounts to AWS Forge config

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/nf-tower-docs#28]
It should be added a mention regarding the *Enable Fusion mounts* in the AWS Forge docs and APIs 

<img width="1079" alt="Screenshot 2020-11-16 at 19 11 27" src="https://user-images.githubusercontent.com/816968/99291180-ae76bd00-283f-11eb-84f1-404f71037ac7.png">

**Comment by abhi18av** [comment]
Already present in point-9  https://help.tower.nf/compute-envs/aws-batch/#forge-compute-environment
