### ISSUE TITLE
Batch of FAQ entries and minor updates based on Freshdesk requests

### ISSUE THREAD

**Issue by llewellyn-sl** [seqeralabs/nf-tower-docs#292]
Addressing the following FD tickets in one fell swoop:

-BitBucket error related to Tower version https://support.seqera.io/a/tickets/2723 
-Tower Agent update fixing "Closing session to reauthenticate" errors https://support.seqera.io/a/tickets/2713 
-CE GPU use based on containerOptions and runOptions params - https://support.seqera.io/a/tickets/2532

Also adding functionality matrix section and overview page for Tower / NF compatibility matrix

**Comment by gwright99** [comment]
Lemme know if you want more details. I was tagging tickets as I saw the need for doc modifications but am not sure all are at 100% yet.

**Comment by llewellyn-sl** [comment]
Done.
