### ISSUE TITLE
Improve the labels allowed characters warning

### ISSUE THREAD

**Issue by mbosio85** [seqeralabs/nf-tower-docs#305]
Currently we show this as a warning for label characters:

>Label names must contain a minimum of 2 and a maximum of 38 alphanumeric characters separated by dashes or underscores and must be unique inside a Workspace

this does not explain that neither name nor value can:
- start with `-` or `_`
- end with `-`  or `_`
- include consecutive strings of `-` `_` : `--`, `__`,`-_`, `_-` 

The lack of explanation generates doubts in customers and issues from adhering to what's written which is not 100% whta's actually allowed

**Comment by llewellyn-sl** [comment]
Addressing as part of 22.4 features doc updates.

**Comment by llewellyn-sl** [comment]
Done.
