### ISSUE TITLE
Docker hub links is broken 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/nf-tower-docs#307]
The link Docker Hub credentials does not work

<img width="1505" alt="Screenshot 2023-01-29 at 21 22 38" src="https://user-images.githubusercontent.com/816968/215353866-384aea2d-0052-4d20-8362-bef593bb084e.png">

**Comment by llewellyn-sl** [comment]
Fixing as part of [this](https://github.com/seqeralabs/nf-tower-docs/pull/309) batch PR.
