### ISSUE TITLE
Secret setup is not correct 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/nf-tower-docs#308]
The execution role should not be changed. The policy should be added the AWS IAM account associated with the credentials added to Tower 

<img width="1548" alt="Screenshot 2023-02-03 at 19 28 10" src="https://user-images.githubusercontent.com/816968/216679985-09ce4735-2c7d-44e8-8f18-ec8ec7096e51.png">

This signal that docs is written without training it. We need to review this process.

**Comment by llewellyn-sl** [comment]
I agree that auditing efforts are needed on old content. Auditing content includes following the existing instructions to determine accuracy, and updating/fixing all outdated/incorrect info. This is high priority.

**Comment by llewellyn-sl** [comment]
It also highlights the importance of technical and language review before publishing.

**Comment by llewellyn-sl** [comment]
Closed by https://github.com/seqeralabs/nf-tower-docs/issues/351. Updates published 01-08-2023
