### ISSUE TITLE
Advanced options docs for AWS Batch Compute env is incomplete

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/nf-tower-docs#314]
The docs for the Advanced options of the AWS Batch compute env is not matching the available settings 

Check 

https://help.tower.nf/22.4/compute-envs/aws-batch/#advanced-options

and 

<img width="590" alt="Screenshot 2023-02-16 at 10 34 41" src="https://user-images.githubusercontent.com/816968/219326110-8896bc8f-04b8-4a30-b8d4-da04ef59b022.png">

**Comment by llewellyn-sl** [comment]
Will address as part of current in-flight doc updates batch.

**Comment by llewellyn-sl** [comment]
Done.
