### ISSUE TITLE
Consolidate Enterprise configuration instructions

### ISSUE THREAD

**Issue by llewellyn-sl** [seqeralabs/nf-tower-docs#360]
The configuration section currently has 10 subpages, most of which should be integrated as sections on the overview page. The layout of the overview page should be condensed and simplified.

**Comment by pditommaso** [comment]
You should consider start making changes into nf-tower-cloud and then copy here. Otherwise they will get out-of-since very soon

**Comment by llewellyn-sl** [comment]
> You should consider start making changes into nf-tower-cloud and then copy here. Otherwise they will get out-of-since very soon

Agreed. Can we automate the copying of the /docs folder to this repo from Cloud every time it is updated on cloud?

**Comment by ewels** [comment]
I've gotten a bit lost on what sites are where and what the plan is now. But sure, happy to help if I can.

**Comment by pditommaso** [comment]
The plan is to move the docs editing in the [nf-tower-docs](https://github.com/seqeralabs/nf-tower-cloud/tree/master/docs) repository and only use this repo for the final publishing (at least until we don't have the documentation website based on Astro).

Therefore ideally, it would be needed a sync that automates the nf-tower-cloud -> nf-tower-docs -> help.tower.nf flow.

**Comment by ewels** [comment]
Do you want the source files in this repo, or do you not care? Can either sync the markdown over to this repo then build, or if not needed then can set up access to them during the docs build stage.

**Comment by pditommaso** [comment]
> Do you want the source files in this repo, or do you not care? 

It's not a strict requirement, but it was more to decouple the nf-tower-cloud repo from docs publishing flow

**Comment by llewellyn-sl** [comment]
The initial idea was to have only the markdown content in the cloud repo (in `~/docs`), then port that content to the docs repo to build and publish. So the mkdocs and other configuration files remain here.

**Comment by ewels** [comment]
Then the easiest is probably to assume that the two repos sit next to one another and symlink the markdown source. This is essentially what I do for the MultiQC docs, works well. The downside is having no markdown in this repo, but if we don't care about that then it's not an issue.

**Comment by ewels** [comment]
Only release? Do we want to have any dev docs in this repo?

**Comment by pditommaso** [comment]
Nope, this should only be Usage + Install public docs

**Comment by ewels** [comment]
Ok, sorry for all the back and forth. So, to recap:

* Usage & Install docs markdown lives in this repo. Develop and push here. 
* Cloud docs live in cloud repo. Develop there.
* On cloud release, copy a snapshot of the cloud docs markdown to this repo
* Build and publish this site whenever the content updates.

Is that right?

**Comment by pditommaso** [comment]
Nope. 

* Usage & Install docs markdown lives in the [nf-tower-docs](https://github.com/seqeralabs/nf-tower-cloud) repo. Changes are made there. 
* On cloud release, a copy of the docs in the release branch is copied here
* Build and publish this site whenever the content updates

**Comment by ewels** [comment]
ok now I'm super confused

> Usage & Install docs markdown lives in the [nf-tower-docs](https://github.com/seqeralabs/nf-tower-cloud) repo.

```markdown
[nf-tower-docs](https://github.com/seqeralabs/nf-tower-cloud) 
```

Text says `nf-tower-docs`  (this repo), link is to `nf-tower-cloud`. Which is it? 😅

**Comment by pditommaso** [comment]
Apologies, it's `nf-tower-cloud` (fixed)

**Comment by ewels** [comment]
ok so all docs live there, website code lives here. That's simpler 👌🏻 

The workflow that springs to mind is something like the following:

* Run the automation on the `nf-tower-cloud` repo, not here
    * Solves any concerns about privacy / accessing the private repo
* Have a GitHub Actions workflow in that repo that triggers on release
* Checks out both repos, copies the files to `nf-tower-docs`, commits + pushes
* Existing GitHub action here responds to the push and builds the new docs.

Should be a pretty simple one to write. Any issues with this approach?

**Comment by gwright99** [comment]
I would like someone to walk CS through how the new world works, please. It seems like the way we've been doing things has been turned inside out, and I would prefer to have someone explain it to me than try to figure it our via GH ticket(s) comments.

**Comment by ewels** [comment]
What it boils down to is basically: the source for the docs are now edited in the `nf-tower-cloud` repo instead of here. The rest is all semantics about how the build works (and me getting confused and thinking it was more complicated than this).

I believe that @llewellyn-sl will write up some new documentation about how the documentation works imminently.

![](https://media.giphy.com/media/9UqRcQHzBou6A/giphy.gif)

**Comment by llewellyn-sl** [comment]
Doc readme updates are in PR on both docs and cloud repos. The configuration consolidation content of this PR has been ported to https://github.com/seqeralabs/nf-tower-cloud/pull/5171
