### ISSUE TITLE
Explain how Datasets work with the launch form

### ISSUE THREAD

**Issue by evanfloden** [seqeralabs/nf-tower-docs#362]
There needs to be more clarity around this topic. We can take the FAQ material we have and add it to/reference in the following places:

https://help.tower.nf/23.1/datasets/overview/#using-a-dataset
https://help.tower.nf/23.1/launch/launchpad/#pipeline-parameters-form
https://help.tower.nf/23.1/pipeline-schema/overview/#customizing-pipeline-schema

**Adapted From the FAQ**

When launching a Nextflow workflow from the Launchpad with a nextflow_schema.json, the input field drop-down will only show Datasets whose mimetypes match the rules specified in the associated nextflow_schema.json file. If your Dataset has a different mimetype than specified in the pipeline schema, Tower will not present the file.

Example: The default [nf-core RNASeq](https://github.com/nf-core/rnaseq) pipeline specifies that only files with a [csv mimetype](https://github.com/nf-core/rnaseq/blob/master/nextflow_schema.json#L18) should be provided as an input file. If you created a Dataset of mimetype tsv, it would not appear as an input filed dropdown option.

**Comment by ewels** [comment]
Quoting @pditommaso:

> The query done using the mimeType. The mimeType is assigned using the file extension: "*.csv" -> "text/csv"

Suggestion: avoid term "mimetype" as quite technical and means different things in different contexts. "File type" with clarification that we mean file extension is probably better for end users, unless we are specifically referring to the field within the JSON schema (pipeline developers).

**Comment by pditommaso** [comment]
Worth noting that in Tower there's no mention of "mimeType". That's a concept that's coming from the nf-core json schema 

<img width="1209" alt="Screenshot 2023-06-13 at 14 22 00" src="https://github.com/seqeralabs/nf-tower-docs/assets/816968/097df812-5bd0-40b9-a249-e30015f3c9a3">

**Comment by ewels** [comment]
Yup, that's because when adding a new dataset it's not yet tied to a pipeline - and so not linked to a schema (right?).

So the mimetype validation can only happen when launching a pipeline and associating a dataset with a workflow.
