### ISSUE TITLE
List of environment variables shows up as a block of code

### ISSUE THREAD

**Issue by bebosudo** [seqeralabs/nf-tower-docs#375]
In https://help.tower.nf/23.1/enterprise/configuration/overview/ when I open one of the dropdown menus named `Environment variables` I see a block of code:
![image](https://github.com/seqeralabs/nf-tower-docs/assets/1922124/fd366191-d8d4-4eed-a24d-3eb729e820f0)
which I suppose it's not meant to happen.

The source code is the following https://github.com/seqeralabs/nf-tower-docs/blob/master/docs/enterprise/configuration/overview.md

Was this broken with the recent/ongoing migration?

**Comment by llewellyn-sl** [comment]
There are substantial updates to this overview page [in flight](https://github.com/seqeralabs/nf-tower-cloud/pull/5171) that will render the config variables and options in tables.
