### ISSUE TITLE
Pipeline Action Docs: Github Webhook Action

### ISSUE THREAD

**Issue by ShahzebMahmood** [seqeralabs/nf-tower-docs#391]
# Background

We have noticed in [this ticket](https://support.seqera.io/a/tickets/3632), The client was unable to create an action using GitHub webhook due to it being greyed out due to the user not signing in to tower with Github. 

# Remediations

The [existing documentation](https://help.tower.nf/23.1/pipeline-actions/overview/) doesn't specify that you must be signed in with Github to create a Github webhook action. I have tested with 'Signing in with Google,' but it does not allow you to create a GitHub webhook action as the 'Add' is greyed out. 

When signed in with GitHub 

![image](https://github.com/seqeralabs/nf-tower-docs/assets/67079312/947968b8-96e7-44e0-a899-26cd0c90150e)

when signed in with Google

![image](https://github.com/seqeralabs/nf-tower-docs/assets/67079312/86960ff9-1b4f-4771-b766-7d7c83741bc4)

**Comment by llewellyn-sl** [comment]
Addressed in https://github.com/seqeralabs/nf-tower-cloud/pull/5660
