### ISSUE TITLE
Make full AWS Parameter Store path clearer

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/nf-tower-docs#410]
The Parameter paths identified in each [subsection](https://help.tower.nf/23.2/enterprise/configuration/overview/) here are only part of the entire necessary path.

There is qualifying text at the top of the page, but it is hidden upon initial load due to being a non-primary tab. It would be worthwhile to consider a better way to communicate the full path to readers.

**Comment by jason-seqera** [comment]
@gwright99, by _Parameter Store_ you're referring to _AWS Parameter Store_? Thanks!

**Comment by gwright99** [comment]
Yes. Title updated for clarity.

**Comment by llewellyn-sl** [comment]
Addressed in https://github.com/seqeralabs/nf-tower-cloud/pull/5660
