### ISSUE TITLE
Highlight that Parameter Store cannot contain all necessary basic configuration entries

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/nf-tower-docs#411]
The Parameter Store method of storing configuration values cannot serve as a self-contained solution. In addition to the called-out `TOWER_ENABLE_AWS_SSM=true` value, other values like the following may also need to be added:

```bash
TOWER_ENABLE_AWS_SSM=true
TOWER_ENABLE_AWS_SES=true
TOWER_ENABLE_PLATFORMS=awsbatch-platform,azbatch-platform
TOWER_ENABLE_UNSAFE_MODE=true
FLYWAY_LOCATIONS=classpath:db-schema/mysql

# Optionally / potentially this value too if tower.yml not used:
TOWER_CONTACT_EMAIL=.....
```

It would be worthwhile to surface this detail more clearly to implementers.

**Comment by llewellyn-sl** [comment]
The first four variables are addressed in https://github.com/seqeralabs/nf-tower-cloud/pull/5660. Excluding FLYWAY_LOCATIONS and TOWER_CONTACT_EMAIL.
