### ISSUE TITLE
Purge support KB folders, add product folders and doc quick links

### ISSUE THREAD

**Issue by llewellyn-sl** [seqeralabs/nf-tower-docs#423]

**Comment by gwright99** [comment]
Rough skeleton of remaining:

![image](https://github.com/seqeralabs/nf-tower-docs/assets/1309341/236847da-91c1-49b9-a1b2-758ee4bcf0ac)

**Comment by gwright99** [comment]
Removed "Quick Links" section (IMO cluttered up front page annd the install / help docs should be in the KB Product sections.

I've kept back-up of original theme, just in case there is disagreement with my actions.

![image](https://github.com/seqeralabs/nf-tower-docs/assets/1309341/e36bdcbf-0d78-4483-962e-55bdd1590a84)

**Comment by gwright99** [comment]
@llewellyn-sl @justinegeffen @jason-seqera - I need to go chase other problems. Can I leave it to one of your to put some basic text into the Product section files pointing back to whatever your IA says is the most appropriate landing page for the various ecosystem products? 

Support will take responsibility for the Support section.

**Comment by llewellyn-sl** [comment]
Published.
