### ISSUE TITLE
UX/docs/product: Personal workspace enhancement copy review

### ISSUE THREAD

**Issue by justinegeffen** [seqeralabs/nf-tower-docs#426]
Review copy around personal workspace enhancement.

**Comment by llewellyn-sl** [comment]
@justinegeffen is this still in review?

**Comment by justinegeffen** [comment]
It is - I've done some rewriting today and awaiting feedback before I close this out.

**Comment by justinegeffen** [comment]
Duplicate of: https://github.com/seqeralabs/nf-tower-docs/issues/504. Closing to minimize confusion. Any tasks related to this work will be added to the referenced issue.
