### ISSUE TITLE
Anchor links hide under the nav bar

### ISSUE THREAD

**Issue by alaincoletta** [seqeralabs/nf-tower-docs#43]
When visiting an anchor link the anchor, the title is at the top of the page under the  nav bar:

http://foo.com/#bar

Actual behaviour:       
+---------------------------------+ 
| BAR///////////////////// header |          
+---------------------------------+
| Here is the rest of the Text    |         
| ...                             |                           
| ...                             |                           
| ...                             |                           
+---------------------------------+

Desired behaviour:
 | //////////////////////// header |
| BAR                                       |
| Here is the rest of the Text    |         
| ...                             |                           
| ...                             |                           
| ...                             |                           
+---------------------------------+

**Comment by rarenatoe** [comment]
This needs to be addressed. It's an annoying effect.

**Comment by abhi18av** [comment]
Closing this as we have transitioned to `mkdocs`.
