### ISSUE TITLE
Harmonize / Elaborate documentation re: LSF (? and other HPC?) resource allocation

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/nf-tower-docs#432]
## Background

As per https://support.seqera.io/a/tickets/3831, a pipeline failed to execute on an LSF HPC due to the presence of two `#BSUB -M` values (first: 0, second: 450).

Conversation on the ticket and a parallel discussion with @robsyme [here](https://seqera.slack.com/archives/D040QCZ6KFT/p1693427038689189) (private 1:1 thread) suggests that this problem was ultimately due to the user not specifying a [`memory` process directive](https://www.nextflow.io/docs/latest/process.html#memory).

I would suggest the documentation suite is not clear that such an action is required:
- The [Tower LSF help entry](https://help.tower.nf/23.2/compute-envs/hpc/#requirements) gives the impression you can set RAM options via cluster-options (along with an Advanced options snippet I don't fully understand - _see screenshot below_).
- The [Nextflow LSF executor](https://www.nextflow.io/docs/latest/executor.html#lsf) documentation does not appear to have anything warning that - while it says ClusterOptions are supported - they aren't supported for RAM definition.
- The [Nextflow ClusterOptions](https://www.nextflow.io/docs/latest/process.html#clusteroptions) also has no warning.

If I did not have access to the SciDev and Nextflow teams, I would not have been able to explain this gotcha. I suspect at least a subset of our customers are in this same boat.

![image](https://github.com/seqeralabs/nf-tower-docs/assets/1309341/cec20f30-5cc2-42b1-84de-3523229e059a)

## Suggested Resolution
1. Clarify how exactly RAM limits can be specified for LSF-type runs:
    1. Can it ever be set via cluster-options (_nextflow.config_ or Tower CE), or must it always be via process directive? 
2. Clarify if this same situation exists for any other resource type (e.g. `queue` and `time` as noted in the ticket).
3. Place appropriate warning(s) in the Nextflow documentation once (1) is accomplished.
4. Place appropriate warning in the Tower LSF documentation reflecting this reality.

**Comment by gwright99** [comment]
@drpatelh @bentsherman @robsyme for awareness (and likelihood they will be contacted as part of this docs effort).

**Comment by bentsherman** [comment]
I guess most users understand that `clusterOptions` is meant to be used as a fallback for options that can't be expressed by process directives. Implicit in that is the warning that using both at the same time may cause undefined behavior, which depends on the executor but usually results in only the first option being used. I suppose we could make this warning explicit in the Nextflow docs [here](https://nextflow.io/docs/edge/process.html#clusteroptions).

It's not that memory settings don't work with `clusterOptions`, it's that you shouldn't use `clusterOptions` and `memory` at the same time. Same goes for the other process directives, which you can see by looking at `LsfExecutor` in Nextflow.

**Comment by gwright99** [comment]
IMO better to assume people don't know (_even if only a subset_) and be explicit about expected norms and best practices. This likely feeds into the sort of work I believe @justinegeffen will be pursuing.
