### ISSUE TITLE
Doc audit: Monitor

### ISSUE THREAD

**Issue by llewellyn-sl** [seqeralabs/nf-tower-docs#450]
Pages:

```
ls -1 docs/monitoring
_images/
aggregate_stats.md
execution.md
overview.md
processes.md
summary.md
tasks.md
```

**Comment by llewellyn-sl** [comment]
An FAQ entry I'm purging from the FAQs page:

- **Tower cost estimation for resumed runs**

The [cost estimator](./monitoring/aggregate_stats.md) value displayed is the **aggregate** value of all compute costs associated with the run (for cached and newly-executed tasks). For example, if you resume your pipeline twice to reach completion, the cost estimate displayed for `<WORKFLOW_NAME>_2` accounts for the costs accrued over all three runs.

**Note:** The Tower cost estimator should only be used for at-a-glance heuristic purposes. For accounting and legal cost reporting, use Tower [resource labels](./resource-labels/overview.md) and leverage your compute platform's native cost reporting tools.

@jason-seqera Please incorporate this into the main aggregate stats page.

**Comment by jason-seqera** [comment]
This happened as well: https://github.com/seqeralabs/nf-tower-cloud/pull/5788

**Comment by jason-seqera** [comment]
PR for this is here: https://github.com/seqeralabs/nf-tower-cloud/pull/5776

**Comment by llewellyn-sl** [comment]
Completed.
