### ISSUE TITLE
Doc audit: Configuration, installation

### ISSUE THREAD

**Issue by llewellyn-sl** [seqeralabs/nf-tower-docs#453]

**Comment by jason-seqera** [comment]
The PR for this is here: https://github.com/seqeralabs/nf-tower-cloud/pull/5818

**Comment by llewellyn-sl** [comment]
@jason-seqera Rob N flagged a broken link in an [issue](https://github.com/seqeralabs/nf-tower-docs/issues/473) that we can fix as part of this issue's PR.

**Comment by llewellyn-sl** [comment]
Completed.
