### ISSUE TITLE
Add FAQ entry for SPOT_PRICE_CAPACITY_OPTIMIZED

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/nf-tower-docs#464]
As per https://github.com/seqeralabs/tower-cli/issues/332, `tw` <= 0.8 does not support operations against AWS Batch CEs using the SPOT_PRICE_CAPACITY_OPTIMIZED allocation strategy.

**[Edited `>=` to `<=`]**

**Comment by llewellyn-sl** [comment]
@gwright99 do you mean tw *<*= 0.8 ?

**Comment by gwright99** [comment]
Arg sorry - multitasking too much. Yes. Fixed in original.

**Comment by llewellyn-sl** [comment]
Addressing in https://github.com/seqeralabs/nf-tower-cloud/pull/5734

**Comment by llewellyn-sl** [comment]
Published.

**Comment by llewellyn-sl** [comment]
Published.
