### ISSUE TITLE
[Docs] Link on Reverse proxy page results in 404 error in v23.2 

### ISSUE THREAD

**Issue by robnewman** [seqeralabs/nf-tower-docs#473]
### Documentation URLs

* https://help.tower.nf/23.2/enterprise/configuration/reverse_proxy/

### Description of issue/improvement

This sentence has a link that results in a 404 Error:

> Use the [Tower frontend unprivileged](https://help.tower.nf/23.2/enterprise/configuration/kubernetes#tower-frontend-unprivileged) image;

### Third party resources

I was reading these docs because we have an open high profile support ticket with the [CDC](https://support.seqera.io/a/tickets/2881).

**Comment by llewellyn-sl** [comment]
Thanks @robnewman! We'll fix that this week as part of our audit.

**Comment by justinegeffen** [comment]
Confirmed fixed.
