### ISSUE TITLE
[docs] Add Wave documentation

### ISSUE THREAD

**Issue by jason-seqera** [seqeralabs/nf-tower-docs#475]
This issue seeks to lift and shift the Wave documentation from https://wavecontainers.io/ to the Tower docs; eventually these will live in a fully branded Wave-specific site.

**Comment by justinegeffen** [comment]
Linked to: https://github.com/seqeralabs/nf-tower-docs/issues/475

**Comment by llewellyn-sl** [comment]
Completed https://github.com/seqeralabs/docs/pull/4
