### ISSUE TITLE
[Docs] Complete list of available tower.yml config

### ISSUE THREAD

**Issue by markpanganiban** [seqeralabs/nf-tower-docs#476]
### Description of issue

GEL is looking for the full list of available configs for tower.yml

https://support.seqera.io/a/tickets/4016

### Customer impact

The client is unsure of what the config is used for

### Type of change/fix

Doc update

### Documentation to be updated on our side

https://help.tower.nf/23.2/enterprise/configuration/overview/

**Comment by llewellyn-sl** [comment]
Duplicate of #474 .
