### ISSUE TITLE
Make sure the grid compute envs reference to latest NF version 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/nf-tower-docs#49]
The configuration of the compute env for batch scheduler: LSF, Slurm, PBS and GridEngine should reference the usage of Nextflow 21.02.0-edge.

**Comment by abhi18av** [comment]
@pditommaso , just to confirm, you mean the version mentioned in the `Requirements` section right?

Also, the PBS one already references the `21.02.0-edge` release.

![image](https://user-images.githubusercontent.com/12799326/108353772-47163380-71c7-11eb-9008-1a5f144485df.png)

**Comment by pditommaso** [comment]
Indeed!
