### ISSUE TITLE
[Docs] Make redis and mysql container uncomment ephemeral lines

### ISSUE THREAD

**Issue by Shahbaz-mahmood123** [seqeralabs/nf-tower-docs#496]
### Description of issue

Uncomment ephemeral lines for both the Redis and MySQL containers:

```
  # enable this snippet to store the Mysql data in the host volume
  #    volumes:
  #      - $HOME/.tower/db/mysql:/var/lib/mysql


  # enable this snippet to store the Redis data in the host volume
  #    volumes:
  #      - $HOME/.tower/db/redis:/data

```

Currently, we explicitly mention this to customers when onboarding and it has caught customers in the past. We should uncomment this and make it default. 

### Customer impact

Prevents customers from using ephemeral containers.

### Type of change/fix

Uncomment lines in yaml file

### Documentation to be updated on our side

https://docs.seqera.io/assets/files/tower-cab3d75ff0e6d80313d5ab89ce6a88a2.yml

**Comment by pditommaso** [comment]
It should also be added a BIG warning that local Redis and Mysql DB should NOT be used for production deployment, and advice instead to use of a corresponding cloud managed service
