### ISSUE TITLE
Include deployment instructions within the Docs

### ISSUE THREAD

**Issue by abhi18av** [seqeralabs/nf-tower-docs#59]
This issue is a placeholder for the current discussions regarding

- unification of the deployment docs into a central location
- adding **minimal** setup instructions as part of the docs

**Comment by abhi18av** [comment]
This could be something like the following 

```
| 
| Installation
|--- Overview (Architecture)
|--- Docker compose
|--- Kubernetes
|--- AWS Marketplace
...
```

Wherein we can use a `Required` alert to tell the users that some setup is expected to be there already and they can continue with the Guide if their infra is ready for the setup.

**Comment by abhi18av** [comment]
We'll be making the `nf-tower-deployment` docs public and using them as references for the `Installation` section in the Tower docs.

**Comment by abhi18av** [comment]
@pditommaso, does the outline mentioned here https://github.com/seqeralabs/nf-tower-docs/issues/59#issuecomment-802295613 make sense? 

If yes, I'd start off the drafts for this.

**Comment by pditommaso** [comment]
I think Marketplace is out of the scope of this repo/guide. ECS may be included instead.

**Comment by abhi18av** [comment]
Okay. But I was thinking that perhaps, since this is a commercial offering wihtout much setup we should mention this in the docs as a `NOTE` - what do you think?

**Comment by pditommaso** [comment]
Don't know, at the end it's just a variation of ECS configuration. I think wont make sense to mention here.

**Comment by abhi18av** [comment]
Based on the discussion done earlier, that we are splitting the deployment docs with the usage docs this issue doesn't make sense.
