### ISSUE TITLE
Docs for the teams feature

### ISSUE THREAD

**Issue by abhi18av** [seqeralabs/nf-tower-docs#62]
@pditommaso , the upcoming features would require use to update the content for most of the pages, plus add new content.

I was wondering whether we could accomplish this using a new section in the docs such as 

```
| ...
| Teams and Workspaces
| ...

```

And within this section we introduce these concepts.

Thoughts?

**Comment by pditommaso** [comment]
I think we should split in: 

* Org & user management 
  - org creation & setting 
  - org members (ie. users)
  - teams (ie. groups)
 * Workspaces 
  - wsp creation & settings 
  - wsp participants 
  - wsp roles

**Comment by abhi18av** [comment]
Cool, it makes sense 👍 

I'll start drafting the docs based on the current state of `teams-feature`.

**Comment by abhi18av** [comment]
@pditommaso , while working on docs  with the structure you mentioned earlier and I found many overlaps and I'm not entirely sure how to segregate them cleanly. 

Here's what I'm thinking at the moment,

- Upgrade older sections to include the concept of Launchpad, upgrade screenshots etc

- New section called - Orgs, Teams and Workspaces with sub-sections explaining the overall usability of various concepts like org, teams and workspaces

**Comment by pditommaso** [comment]
Make sense, go ahead. Try keep to use screen shoot only to essential and focus more on the description. Tx!
