### ISSUE TITLE
Add a new "Customizing Tower" section

### ISSUE THREAD

**Issue by abhi18av** [seqeralabs/nf-tower-docs#68]
@pditommaso , I was thinking that we should add a new section which talks about how people can customize Tower, for example things like Authentication setup , Access allow pattern, Menu customization mentioned [here](https://github.com/seqeralabs/nf-tower-deployment/blob/master/config.md#configure-user-access-allow-list) could be covered within the centralized documentation.

I think that it's better to provide a single source of docs for the users.

Thoughts?

**Comment by pditommaso** [comment]
Not convinced about single repo for all docs. Users documentation target very different people from installation docs. Also in the near future product can diverge in terms of feature. 

I even think we should remove the installation docs from help.tower.nf

**Comment by abhi18av** [comment]
> Users documentation target very different people from installation docs 

I do understand and agree to this thought, there are quite a diverse group of people we are catering 👍 

I'm closing this issue since we have decided to essentially keep these docs separate.
