### ISSUE TITLE
Broken links throughout the documentation

### ISSUE THREAD

**Issue by dburkhardt** [seqeralabs/nf-tower-docs#82]
Almost all of the links on this page are broken: https://help.tower.nf/monitoring/execution.html including:
> Summary and status section.
List of pipeline processes.
Aggregated stats and load.

Image link on this page is broken: https://help.tower.nf/monitoring/processes.html

**Comment by pditommaso** [comment]
thanks for reporting! 🤦

**Comment by abhi18av** [comment]
Well spotted @dburkhardt !

The recent changes in `mkdocs-material` are backward incompatible and https://github.com/seqeralabs/nf-tower-docs/pull/83 should fix these issues.

**Comment by abhi18av** [comment]
@dburkhardt , please note that the links you've shared earlier are no longer valid with the pinned version `mkdocs-material` we are using now.

Try the following (without the `.html`) to access the pages

https://help.tower.nf/monitoring/execution
https://help.tower.nf/monitoring/processes
